version: '3.9'

services:
  redis-virtual-queue:
    image: redis:8.0-M01
    container_name: redis-local
    ports:
      - "6379:6379"

  rabbitmq-virtual-queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-virtual-queue: 
    build: 
      dockerfile: ./virtual-queue/Dockerfile.api
    command: >
      dockerize -wait tcp://redis-virtual-queue:6379 -wait tcp://rabbitmq-virtual-queue:5672 -timeout 40s
      go run ./cmd/api/main.go
    volumes:
      - ./virtual-queue:/app
    # ports:
    #   - 3000:3000
    deploy:
      replicas: 2
    depends_on:
      - redis-virtual-queue
      - rabbitmq-virtual-queue

  websocket-virtual-queue: 
    build: 
      dockerfile: ./virtual-queue/Dockerfile.websocket
    command: >
      dockerize -wait tcp://rabbitmq-virtual-queue:5672 -timeout 40s
      go run ./cmd/websocket/main.go
    volumes:
      - ./virtual-queue:/app
    # ports:
    #   - 5001:5001
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq-virtual-queue

  worker-virtual-queue: 
    build:
      dockerfile: ./virtual-queue/Dockerfile.worker
    command: >
      dockerize -wait tcp://redis-virtual-queue:6379 -wait tcp://rabbitmq-virtual-queue:5672 -timeout 40s
      go run ./cmd/worker/main.go
    volumes:
      - ./virtual-queue:/app
    depends_on:
      - redis-virtual-queue
      - rabbitmq-virtual-queue

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api-virtual-queue
      - websocket-virtual-queue

  redis-ticket-purchase:
    image: redis:8.0-M01
    container_name: redis-local-2
    ports:
      - "6380:6379"

  mysql-ticket-purchase:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventim
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./ticket-purchase/.docker/mysql:/var/lib/mysql
      - ./ticket-purchase/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-ticket-purchase: 
    build: 
      dockerfile: ./ticket-purchase/Dockerfile.api
    command: >
      dockerize -wait tcp://redis-virtual-queue:6379 -wait tcp://rabbitmq-virtual-queue:5672 -timeout 40s
      go run ./cmd/api/main.go
    volumes:
      - ./ticket-purchase:/app
    ports:
      - 3001:3001
    depends_on:
      - redis-ticket-purchase
      - mysql-ticket-purchase