version: '3.9'

services:
  redis-virtual-queue:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"

  rabbitmq-virtual-queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest