
POST http://localhost/api/tickets/reserve HTTP/1.1
Content-Type: application/json

{
    "user_token": "5c746e0fc522604c83157316a521c02f8fb0d0ad62df40e023a324f665fc4bc7",
    "quantity": 1
}

###
POST http://localhost/api/tickets/purchase HTTP/1.1
Content-Type: application/json

{
    "user_token": "b6c0fdd5175d7b2b070268b25769823f76053876a4d0cb32599e4e5af14a431f"
}